= Documentaion proyecto primer parcial
daniel meza
:doctype: book
:toc: 
:imagesdir: Images
:sectnums: 
:toclevels: 3
:chapter-label: Section

== Project description

No description found (add content in project description)

== Code component descriptions

=== DQMH(R) modules

This section describes DQMH(R) module responsibilities and relationships.

==== Preamble

A DQMH module is the main component of an architecture based on DQMH(R) framework. A DQMH module is used to implement a section of the application that has one responsibility.

DQMH(R) framework defines two different type of DQMH module.  

====
*Singleton:*

A Singleton DQMH module can have only one instance running at any given time.
====

====
*Cloneable:*

A Cloneable DQMH module can have one or multiple instances running in parallel.
====

DQMH(R) framework defines two different ways to carry data throughout the application and with both other DQMH modules and non-DQMH based code.

====
*Request events:*

A request is a code that fires an event requesting the DQMH module to do something. Multiple locations in the code can send events to the DQMH module.

Request events are many-to-one.

Requests are usually named using imperative tense.
====

====
*Broadcast events:*

A broadcast is a code that fires an event broadcasting that the DQMH module did something. Multiple Event Structures can register to handle the Broadcast Events.

Broadcast Events are one-to-many.

Broadcasts are usually named using past tense or passive voice.
====

NOTE: Refer to the DQMH(R) framework official http://delacor.com/documentation/dqmh-html/[documentation] to find more details on how the framework works


The following section gives you details on the project architecture relying on this framework.
It gives you an overview of the modules' interaction and detailed information on each module.

Graphs used in this section have the following legend:

*Components:*


[graphviz, format="png", align="center"]
....
digraph G272712 {
rankdir=LR;
edge[dir=both color=black  arrowhead=normal arrowtail=none style=filled penwidth=1]
node[color=black shape=box]
"DQMH module / Lvlib"[color=black shape=component]
"Vi"[color=skyblue shape=note]
}
....

*Events:*

[graphviz, format="png", align="center"]
....
digraph G9943 {
rankdir=LR;
edge[dir=both color=black  arrowhead=normal arrowtail=none style=filled penwidth=1]
node[color=black shape=box]
" "[color=white shape=box]
"  "[color=white shape=box]
"   "[color=white shape=box]
"    "[color=white shape=box]
" " -> "  " [label="Request to a DQMH module" dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"   " -> "    " [label="Broadcast from a DQMH module" dir=both color=goldenrod  arrowhead=normal arrowtail=none style=dashed penwidth=1];
}
....

*Start and Stop module callers:*

[graphviz, format="png", align="center"]
....
digraph G566788 {
rankdir=LR;
edge[dir=both color=black  arrowhead=normal arrowtail=none style=filled penwidth=1]
node[color=black shape=box]
"Start Module
caller"[color=black shape=component]
"Start Module"[color=yellowgreen shape=note]
"Start Module" -> "Start Module
caller" [label="Called by" dir=both color=yellowgreen  arrowhead=odot arrowtail=inv style=filled penwidth=1];
}
....

[graphviz, format="png", align="center"]
....
digraph G514769 {
rankdir=LR;
edge[dir=both color=black  arrowhead=normal arrowtail=none style=filled penwidth=1]
node[color=black shape=box]
"Stop Module
caller"[color=black shape=component]
"Stop Module"[color=tomato shape=note]
"Stop Module" -> "Stop Module
caller" [label="Called by" dir=both color=tomato  arrowhead=odot arrowtail=inv style=dotted penwidth=1];
}
....


==== Modules overview

This project contains the following modules.

.Modules list
|===
|Singleton|Cloneable

|<<Config.lvlib>>
|

|<<Mensajes.lvlib>>
|

|<<Monedas.lvlib>>
|

|<<Producto.lvlib>>
|

|<<UI.lvlib>>
|
|===

This graph represents the links between all DQMH modules.

[graphviz, format="png", align="center"]
....
digraph G135021 {
rankdir=LR;
edge[dir=both color=black  arrowhead=normal arrowtail=none style=filled penwidth=1]
node[color=black shape=box]
"UI"[color=black shape=component]
"Config"[color=black shape=component]
"Mensajes"[color=black shape=component]
"Monedas"[color=black shape=component]
"Producto"[color=black shape=component]
"Config" -> "Config" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"UI" -> "Config" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Config" -> "UI" [label=" " dir=both color=goldenrod  arrowhead=normal arrowtail=none style=dashed penwidth=1];
"Mensajes" -> "Mensajes" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"UI" -> "Mensajes" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Monedas" -> "Mensajes" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"UI" -> "Monedas" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Monedas" -> "Monedas" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Monedas" -> "Producto" [label=" " dir=both color=goldenrod  arrowhead=normal arrowtail=none style=dashed penwidth=1];
"UI" -> "Producto" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Producto" -> "Producto" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Mensajes" -> "Producto" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Producto" -> "UI" [label=" " dir=both color=goldenrod  arrowhead=normal arrowtail=none style=dashed penwidth=1];
"UI" -> "UI" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
}
....


==== Config.lvlib

*Type:* Singleton

*Responsibility*: No description found (add content in DQMH module lvlib description)

===== Module Start/Stop calls

[graphviz, format="png", align="center"]
....
digraph G342311 {
rankdir=LR;
edge[dir=both color=black  arrowhead=normal arrowtail=none style=filled penwidth=1]
node[color=black shape=box]
"Start Module"[color=yellowgreen shape=note]
"UI"[color=black shape=component]
"Test Config API"[color=skyblue shape=note]
"Stop Module"[color=tomato shape=note]
"Config"[color=black shape=component]
"Start Module" -> "UI" [dir=both color=yellowgreen  arrowhead=odot arrowtail=inv style=filled penwidth=1];
"Start Module" -> "Test Config API" [dir=both color=yellowgreen  arrowhead=odot arrowtail=inv style=filled penwidth=1];
"Stop Module" -> "Config" [dir=both color=tomato  arrowhead=odot arrowtail=inv style=dotted penwidth=1];
"Stop Module" -> "UI" [dir=both color=tomato  arrowhead=odot arrowtail=inv style=dotted penwidth=1];
"Stop Module" -> "Test Config API" [dir=both color=tomato  arrowhead=odot arrowtail=inv style=dotted penwidth=1];
}
....

.Start and Stop module callers
|===
|Function|Callers

|<<Config.lvlib:Start Module.vi>>
|UI.lvlib:Main.vi +
Test Config API.vi

|<<Config.lvlib:Stop Module.vi>>
|Config.lvlib:Handle Exit.vi +
UI.lvlib:Main.vi +
Test Config API.vi
|===

===== Module relationship

[graphviz, format="png", align="center"]
....
digraph G37827 {
rankdir=LR;
edge[dir=both color=black  arrowhead=normal arrowtail=none style=filled penwidth=1]
node[color=black shape=box]
"Config"[color=slateblue shape=component]
"UI"[color=black shape=component]
"Test Config API"[color=skyblue shape=note]
"UI" -> "Config" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Test Config API" -> "Config" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Config" -> "Config" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Config" -> "UI" [label=" " dir=both color=goldenrod  arrowhead=normal arrowtail=none style=dashed penwidth=1];
"Config" -> "Test Config API" [label=" " dir=both color=goldenrod  arrowhead=normal arrowtail=none style=dashed penwidth=1];
"Config" -> "Config" [label="   " dir=both color=forestgreen  arrowhead=onormal arrowtail=none style=filled penwidth=1];
}
....

.Requests callers
|===
|Request Name|Callers

|<<Config.lvlib:Show Panel.vi>>
|UI.lvlib:Main.vi +
Test Config API.vi

|<<Config.lvlib:Hide Panel.vi>>
|Test Config API.vi

|<<Config.lvlib:Get Module Execution Status.vi>>
|Config.lvlib:Start Module.vi +
Config.lvlib:Obtain Broadcast Events for Registration.vi

|<<Config.lvlib:Show Diagram.vi>>
|Test Config API.vi
|===

.Broadcasts Listeners
|===
|Broadcast Name|Listeners

|<<Config.lvlib:Module Did Init.vi>>
|UI.lvlib:Main.vi +
Test Config API.vi

|<<Config.lvlib:Status Updated.vi>>
|Test Config API.vi

|<<Config.lvlib:Error Reported.vi>>
|Test Config API.vi

|<<Config.lvlib:Module Did Stop.vi>>
|Test Config API.vi

|<<Config.lvlib:Update Module Execution Status.vi>>
|Test Config API.vi
|===

.Used requests
|===
|Module|Brodcasts

|<<Config.lvlib>>
|Config.lvlib:Get Module Execution Status.vi
|===

.Registred broadcast
|===
|Module|Brodcasts

|--
|--
|===

==== Mensajes.lvlib

*Type:* Singleton

*Responsibility*: No description found (add content in DQMH module lvlib description)

===== Module Start/Stop calls

[graphviz, format="png", align="center"]
....
digraph G94992 {
rankdir=LR;
edge[dir=both color=black  arrowhead=normal arrowtail=none style=filled penwidth=1]
node[color=black shape=box]
"Start Module"[color=yellowgreen shape=note]
"UI"[color=black shape=component]
"Test Mensajes API"[color=skyblue shape=note]
"Stop Module"[color=tomato shape=note]
"Mensajes"[color=black shape=component]
"Start Module" -> "UI" [dir=both color=yellowgreen  arrowhead=odot arrowtail=inv style=filled penwidth=1];
"Start Module" -> "Test Mensajes API" [dir=both color=yellowgreen  arrowhead=odot arrowtail=inv style=filled penwidth=1];
"Stop Module" -> "Mensajes" [dir=both color=tomato  arrowhead=odot arrowtail=inv style=dotted penwidth=1];
"Stop Module" -> "UI" [dir=both color=tomato  arrowhead=odot arrowtail=inv style=dotted penwidth=1];
"Stop Module" -> "Test Mensajes API" [dir=both color=tomato  arrowhead=odot arrowtail=inv style=dotted penwidth=1];
}
....

.Start and Stop module callers
|===
|Function|Callers

|<<Mensajes.lvlib:Start Module.vi>>
|UI.lvlib:Main.vi +
Test Mensajes API.vi

|<<Mensajes.lvlib:Stop Module.vi>>
|Mensajes.lvlib:Handle Exit.vi +
UI.lvlib:Main.vi +
Test Mensajes API.vi
|===

===== Module relationship

[graphviz, format="png", align="center"]
....
digraph G701096 {
rankdir=LR;
edge[dir=both color=black  arrowhead=normal arrowtail=none style=filled penwidth=1]
node[color=black shape=box]
"Mensajes"[color=slateblue shape=component]
"UI"[color=black shape=component]
"Test Mensajes API"[color=skyblue shape=note]
"Monedas"[color=black shape=component]
"Producto"[color=black shape=component]
"UI" -> "Mensajes" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Test Mensajes API" -> "Mensajes" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Mensajes" -> "Mensajes" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Monedas" -> "Mensajes" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Mensajes" -> "Test Mensajes API" [label=" " dir=both color=goldenrod  arrowhead=normal arrowtail=none style=dashed penwidth=1];
"Mensajes" -> "Mensajes" [label="   " dir=both color=forestgreen  arrowhead=onormal arrowtail=none style=filled penwidth=1];
"Mensajes" -> "Producto" [label="   " dir=both color=forestgreen  arrowhead=onormal arrowtail=none style=filled penwidth=1];
}
....

.Requests callers
|===
|Request Name|Callers

|<<Mensajes.lvlib:Show Panel.vi>>
|Test Mensajes API.vi

|<<Mensajes.lvlib:Hide Panel.vi>>
|Test Mensajes API.vi

|<<Mensajes.lvlib:Get Module Execution Status.vi>>
|Mensajes.lvlib:Start Module.vi +
Mensajes.lvlib:Obtain Broadcast Events for Registration.vi

|<<Mensajes.lvlib:Show Diagram.vi>>
|Test Mensajes API.vi

|<<Mensajes.lvlib:Publicar mensaje.vi>>
|Monedas.lvlib:Main.vi +
UI.lvlib:Main.vi +
Test Mensajes API.vi

|<<Mensajes.lvlib:actualizar el credito.vi>>
|Monedas.lvlib:Main.vi +
Test Mensajes API.vi

|<<Mensajes.lvlib:Compra Realizada.vi>>
|Test Mensajes API.vi
|===

.Broadcasts Listeners
|===
|Broadcast Name|Listeners

|<<Mensajes.lvlib:Module Did Init.vi>>
|Test Mensajes API.vi

|<<Mensajes.lvlib:Status Updated.vi>>
|Test Mensajes API.vi

|<<Mensajes.lvlib:Error Reported.vi>>
|Test Mensajes API.vi

|<<Mensajes.lvlib:Module Did Stop.vi>>
|Test Mensajes API.vi

|<<Mensajes.lvlib:Update Module Execution Status.vi>>
|Test Mensajes API.vi
|===

.Used requests
|===
|Module|Brodcasts

|<<Mensajes.lvlib>>
|Mensajes.lvlib:Get Module Execution Status.vi

|<<Producto.lvlib>>
|Producto.lvlib:Actualizar inventario.vi
|===

.Registred broadcast
|===
|Module|Brodcasts

|--
|--
|===

==== Monedas.lvlib

*Type:* Singleton

*Responsibility*: No description found (add content in DQMH module lvlib description)

===== Module Start/Stop calls

[graphviz, format="png", align="center"]
....
digraph G184864 {
rankdir=LR;
edge[dir=both color=black  arrowhead=normal arrowtail=none style=filled penwidth=1]
node[color=black shape=box]
"Start Module"[color=yellowgreen shape=note]
"UI"[color=black shape=component]
"Test Monedas API"[color=skyblue shape=note]
"Stop Module"[color=tomato shape=note]
"Monedas"[color=black shape=component]
"Start Module" -> "UI" [dir=both color=yellowgreen  arrowhead=odot arrowtail=inv style=filled penwidth=1];
"Start Module" -> "Test Monedas API" [dir=both color=yellowgreen  arrowhead=odot arrowtail=inv style=filled penwidth=1];
"Stop Module" -> "Monedas" [dir=both color=tomato  arrowhead=odot arrowtail=inv style=dotted penwidth=1];
"Stop Module" -> "UI" [dir=both color=tomato  arrowhead=odot arrowtail=inv style=dotted penwidth=1];
"Stop Module" -> "Test Monedas API" [dir=both color=tomato  arrowhead=odot arrowtail=inv style=dotted penwidth=1];
}
....

.Start and Stop module callers
|===
|Function|Callers

|<<Monedas.lvlib:Start Module.vi>>
|UI.lvlib:Main.vi +
Test Monedas API.vi

|<<Monedas.lvlib:Stop Module.vi>>
|Monedas.lvlib:Handle Exit.vi +
UI.lvlib:Main.vi +
Test Monedas API.vi
|===

===== Module relationship

[graphviz, format="png", align="center"]
....
digraph G174417 {
rankdir=LR;
edge[dir=both color=black  arrowhead=normal arrowtail=none style=filled penwidth=1]
node[color=black shape=box]
"Monedas"[color=slateblue shape=component]
"UI"[color=black shape=component]
"Test Monedas API"[color=skyblue shape=note]
"Producto"[color=black shape=component]
"Mensajes"[color=black shape=component]
"UI" -> "Monedas" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Test Monedas API" -> "Monedas" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Monedas" -> "Monedas" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Monedas" -> "Test Monedas API" [label=" " dir=both color=goldenrod  arrowhead=normal arrowtail=none style=dashed penwidth=1];
"Monedas" -> "Producto" [label=" " dir=both color=goldenrod  arrowhead=normal arrowtail=none style=dashed penwidth=1];
"Monedas" -> "Mensajes" [label="   " dir=both color=forestgreen  arrowhead=onormal arrowtail=none style=filled penwidth=1];
"Monedas" -> "Monedas" [label="   " dir=both color=forestgreen  arrowhead=onormal arrowtail=none style=filled penwidth=1];
}
....

.Requests callers
|===
|Request Name|Callers

|<<Monedas.lvlib:Show Panel.vi>>
|Test Monedas API.vi

|<<Monedas.lvlib:Hide Panel.vi>>
|Test Monedas API.vi

|<<Monedas.lvlib:Get Module Execution Status.vi>>
|Monedas.lvlib:Obtain Broadcast Events for Registration.vi +
Monedas.lvlib:Start Module.vi

|<<Monedas.lvlib:Show Diagram.vi>>
|Test Monedas API.vi

|<<Monedas.lvlib:botones uno, dos, tres, cuatro.vi>>
|Test Monedas API.vi

|<<Monedas.lvlib:Set Coins Valuessssss.vi>>
|Test Monedas API.vi
|===

.Broadcasts Listeners
|===
|Broadcast Name|Listeners

|<<Monedas.lvlib:Module Did Init.vi>>
|Test Monedas API.vi

|<<Monedas.lvlib:Status Updated.vi>>
|Test Monedas API.vi

|<<Monedas.lvlib:Error Reported.vi>>
|Test Monedas API.vi

|<<Monedas.lvlib:Module Did Stop.vi>>
|Test Monedas API.vi

|<<Monedas.lvlib:Update Module Execution Status.vi>>
|Producto.lvlib:Main.vi +
Test Monedas API.vi
|===

.Used requests
|===
|Module|Brodcasts

|<<Mensajes.lvlib>>
|Mensajes.lvlib:Publicar mensaje.vi +
Mensajes.lvlib:actualizar el credito.vi

|<<Monedas.lvlib>>
|Monedas.lvlib:Get Module Execution Status.vi
|===

.Registred broadcast
|===
|Module|Brodcasts

|--
|--
|===

==== Producto.lvlib

*Type:* Singleton

*Responsibility*: No description found (add content in DQMH module lvlib description)

===== Module Start/Stop calls

[graphviz, format="png", align="center"]
....
digraph G575427 {
rankdir=LR;
edge[dir=both color=black  arrowhead=normal arrowtail=none style=filled penwidth=1]
node[color=black shape=box]
"Start Module"[color=yellowgreen shape=note]
"UI"[color=black shape=component]
"Test Producto API"[color=skyblue shape=note]
"Stop Module"[color=tomato shape=note]
"Producto"[color=black shape=component]
"Start Module" -> "UI" [dir=both color=yellowgreen  arrowhead=odot arrowtail=inv style=filled penwidth=1];
"Start Module" -> "Test Producto API" [dir=both color=yellowgreen  arrowhead=odot arrowtail=inv style=filled penwidth=1];
"Stop Module" -> "Producto" [dir=both color=tomato  arrowhead=odot arrowtail=inv style=dotted penwidth=1];
"Stop Module" -> "UI" [dir=both color=tomato  arrowhead=odot arrowtail=inv style=dotted penwidth=1];
"Stop Module" -> "Test Producto API" [dir=both color=tomato  arrowhead=odot arrowtail=inv style=dotted penwidth=1];
}
....

.Start and Stop module callers
|===
|Function|Callers

|<<Producto.lvlib:Start Module.vi>>
|UI.lvlib:Main.vi +
Test Producto API.vi

|<<Producto.lvlib:Stop Module.vi>>
|Producto.lvlib:Handle Exit.vi +
UI.lvlib:Main.vi +
Test Producto API.vi
|===

===== Module relationship

[graphviz, format="png", align="center"]
....
digraph G343558 {
rankdir=LR;
edge[dir=both color=black  arrowhead=normal arrowtail=none style=filled penwidth=1]
node[color=black shape=box]
"Producto"[color=slateblue shape=component]
"UI"[color=black shape=component]
"Test Producto API"[color=skyblue shape=note]
"Mensajes"[color=black shape=component]
"Monedas"[color=black shape=component]
"UI" -> "Producto" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Test Producto API" -> "Producto" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Producto" -> "Producto" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Mensajes" -> "Producto" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Producto" -> "UI" [label=" " dir=both color=goldenrod  arrowhead=normal arrowtail=none style=dashed penwidth=1];
"Producto" -> "Test Producto API" [label=" " dir=both color=goldenrod  arrowhead=normal arrowtail=none style=dashed penwidth=1];
"Monedas" -> "Producto" [label="  " dir=both color=goldenrod  arrowhead=onormal arrowtail=none style=dashed penwidth=1];
"Producto" -> "Producto" [label="   " dir=both color=forestgreen  arrowhead=onormal arrowtail=none style=filled penwidth=1];
}
....

.Requests callers
|===
|Request Name|Callers

|<<Producto.lvlib:Show Panel.vi>>
|Test Producto API.vi

|<<Producto.lvlib:Hide Panel.vi>>
|Test Producto API.vi

|<<Producto.lvlib:Get Module Execution Status.vi>>
|Producto.lvlib:Obtain Broadcast Events for Registration.vi +
Producto.lvlib:Start Module.vi

|<<Producto.lvlib:Show Diagram.vi>>
|Test Producto API.vi

|<<Producto.lvlib:Set Products.vi>>
|Producto.lvlib:Main.vi +
Test Producto API.vi

|<<Producto.lvlib:Actualizar inventario.vi>>
|Mensajes.lvlib:Main.vi +
Producto.lvlib:Main.vi +
Test Producto API.vi
|===

.Broadcasts Listeners
|===
|Broadcast Name|Listeners

|<<Producto.lvlib:Module Did Init.vi>>
|UI.lvlib:Main.vi +
Test Producto API.vi

|<<Producto.lvlib:Status Updated.vi>>
|Test Producto API.vi

|<<Producto.lvlib:Error Reported.vi>>
|Test Producto API.vi

|<<Producto.lvlib:Module Did Stop.vi>>
|Test Producto API.vi

|<<Producto.lvlib:Update Module Execution Status.vi>>
|Test Producto API.vi
|===

.Used requests
|===
|Module|Brodcasts

|<<Producto.lvlib>>
|Producto.lvlib:Get Module Execution Status.vi +
Producto.lvlib:Set Products.vi +
Producto.lvlib:Actualizar inventario.vi
|===

.Registred broadcast
|===
|Module|Brodcasts

|<<Monedas.lvlib>>
|Update Module Execution Status.vi
|===

==== UI.lvlib

*Type:* Singleton

*Responsibility*: No description found (add content in DQMH module lvlib description)

===== Module Start/Stop calls

[graphviz, format="png", align="center"]
....
digraph G897664 {
rankdir=LR;
edge[dir=both color=black  arrowhead=normal arrowtail=none style=filled penwidth=1]
node[color=black shape=box]
"Start Module"[color=yellowgreen shape=note]
"Test UI API"[color=skyblue shape=note]
"Stop Module"[color=tomato shape=note]
"UI"[color=black shape=component]
"Start Module" -> "Test UI API" [dir=both color=yellowgreen  arrowhead=odot arrowtail=inv style=filled penwidth=1];
"Stop Module" -> "UI" [dir=both color=tomato  arrowhead=odot arrowtail=inv style=dotted penwidth=1];
"Stop Module" -> "Test UI API" [dir=both color=tomato  arrowhead=odot arrowtail=inv style=dotted penwidth=1];
}
....

.Start and Stop module callers
|===
|Function|Callers

|<<UI.lvlib:Start Module.vi>>
|Test UI API.vi

|<<UI.lvlib:Stop Module.vi>>
|UI.lvlib:Handle Exit.vi +
Test UI API.vi
|===

===== Module relationship

[graphviz, format="png", align="center"]
....
digraph G918640 {
rankdir=LR;
edge[dir=both color=black  arrowhead=normal arrowtail=none style=filled penwidth=1]
node[color=black shape=box]
"UI"[color=slateblue shape=component]
"Test UI API"[color=skyblue shape=note]
"Config"[color=black shape=component]
"Mensajes"[color=black shape=component]
"Test UI API" -> "UI" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"UI" -> "UI" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"UI" -> "Test UI API" [label=" " dir=both color=goldenrod  arrowhead=normal arrowtail=none style=dashed penwidth=1];
"Config" -> "UI" [label="  " dir=both color=goldenrod  arrowhead=onormal arrowtail=none style=dashed penwidth=1];
"UI" -> "Config" [label="   " dir=both color=forestgreen  arrowhead=onormal arrowtail=none style=filled penwidth=1];
"UI" -> "Mensajes" [label="   " dir=both color=forestgreen  arrowhead=onormal arrowtail=none style=filled penwidth=1];
"UI" -> "UI" [label="   " dir=both color=forestgreen  arrowhead=onormal arrowtail=none style=filled penwidth=1];
}
....

.Requests callers
|===
|Request Name|Callers

|<<UI.lvlib:Show Panel.vi>>
|Test UI API.vi

|<<UI.lvlib:Hide Panel.vi>>
|Test UI API.vi

|<<UI.lvlib:Get Module Execution Status.vi>>
|UI.lvlib:Start Module.vi +
UI.lvlib:Obtain Broadcast Events for Registration.vi

|<<UI.lvlib:Show Diagram.vi>>
|Test UI API.vi
|===

.Broadcasts Listeners
|===
|Broadcast Name|Listeners

|<<UI.lvlib:Module Did Init.vi>>
|Test UI API.vi

|<<UI.lvlib:Status Updated.vi>>
|Test UI API.vi

|<<UI.lvlib:Error Reported.vi>>
|Test UI API.vi

|<<UI.lvlib:Module Did Stop.vi>>
|Test UI API.vi

|<<UI.lvlib:Update Module Execution Status.vi>>
|Test UI API.vi
|===

.Used requests
|===
|Module|Brodcasts

|<<Config.lvlib>>
|Config.lvlib:Show Panel.vi

|<<Mensajes.lvlib>>
|Mensajes.lvlib:Publicar mensaje.vi

|<<UI.lvlib>>
|UI.lvlib:Get Module Execution Status.vi
|===

.Registred broadcast
|===
|Module|Brodcasts

|<<Config.lvlib>>
|Module Did Init.vi
|===

=== Libraries

This section describes the libraries contained in the project.

==== DataBaseSQLlite.lvlib

No description found (add content in lvlib description)


=== Classes

This section describes the classes contained in the project.

== VI descriptions

=== DQMH(R) modules

This section describes DQMH(R) modules events.

==== Config.lvlib

===== Config.lvlib:Start Module.vi

*Event type:* Not a DQMH Event

:imgpath: Config.lvlib_Start Module.vi.png
image::{imgpath}[Config.lvlib:Start Module.vi]

*Description:*
++++
Launches the Module Main.vi.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Config.lvlib:Stop Module.vi

*Event type:* Not a DQMH Event

:imgpath: Config.lvlib_Stop Module.vi.png
image::{imgpath}[Config.lvlib:Stop Module.vi]

*Description:*
++++
Send the Stop request to the Module's Main.vi.

If <b>Wait for Module to Stop?</b> is TRUE, this VI will wait until the module main VI stops, and will timeout at the <b>Timeout to Wait for Stop</b> value. This value defaults to "-1", which means the VI will not timeout, and will always wait until the module main VI stops before completing execution.

Note: The <b>Timeout to Wait for Stop</b> value is ignored if 'Wait for Module to Stop?' is set to FALSE.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Config.lvlib:Show Panel.vi

*Event type:* Request

:imgpath: Config.lvlib_Show Panel.vi.png
image::{imgpath}[Config.lvlib:Show Panel.vi]

*Description:*
++++
Send the Show Panel request to the Module's Main.vi.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Config.lvlib:Hide Panel.vi

*Event type:* Request

:imgpath: Config.lvlib_Hide Panel.vi.png
image::{imgpath}[Config.lvlib:Hide Panel.vi]

*Description:*
++++
Send the Hide Panel request to the Module's Main.vi.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Config.lvlib:Get Module Execution Status.vi

*Event type:* Request

:imgpath: Config.lvlib_Get Module Execution Status.vi.png
image::{imgpath}[Config.lvlib:Get Module Execution Status.vi]

*Description:*
++++
Fire the Get Module Execution Status request.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Config.lvlib:Show Diagram.vi

*Event type:* Request

:imgpath: Config.lvlib_Show Diagram.vi.png
image::{imgpath}[Config.lvlib:Show Diagram.vi]

*Description:*
++++
This VI tells the Module to show its block diagram to facilitate troubleshooting (add probes, breakpoints, highlight execution, etc).

_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Config.lvlib:Module Did Init.vi

*Event type:* Broadcast

:imgpath: Config.lvlib_Module Did Init.vi.png
image::{imgpath}[Config.lvlib:Module Did Init.vi]

*Description:*
++++
Send the Module Did Init event to any VI registered to listen to this module's broadcast events.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Config.lvlib:Status Updated.vi

*Event type:* Broadcast

:imgpath: Config.lvlib_Status Updated.vi.png
image::{imgpath}[Config.lvlib:Status Updated.vi]

*Description:*
++++
Send the Status Updated event to any VI registered to listen to events from the owning module.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Config.lvlib:Error Reported.vi

*Event type:* Broadcast

:imgpath: Config.lvlib_Error Reported.vi.png
image::{imgpath}[Config.lvlib:Error Reported.vi]

*Description:*
++++
Send the Error Reported event to any VI registered to listen to events from the owning module.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Config.lvlib:Module Did Stop.vi

*Event type:* Broadcast

:imgpath: Config.lvlib_Module Did Stop.vi.png
image::{imgpath}[Config.lvlib:Module Did Stop.vi]

*Description:*
++++
Send the Module Did Stop event to any VI registered to listen to this module's broadcast events.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Config.lvlib:Update Module Execution Status.vi

*Event type:* Broadcast

:imgpath: Config.lvlib_Update Module Execution Status.vi.png
image::{imgpath}[Config.lvlib:Update Module Execution Status.vi]

*Description:*
++++
Broadcast event to specify whether or not the module is running.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

==== Mensajes.lvlib

===== Mensajes.lvlib:Start Module.vi

*Event type:* Not a DQMH Event

:imgpath: Mensajes.lvlib_Start Module.vi.png
image::{imgpath}[Mensajes.lvlib:Start Module.vi]

*Description:*
++++
Launches the Module Main.vi.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Mensajes.lvlib:Stop Module.vi

*Event type:* Not a DQMH Event

:imgpath: Mensajes.lvlib_Stop Module.vi.png
image::{imgpath}[Mensajes.lvlib:Stop Module.vi]

*Description:*
++++
Send the Stop request to the Module's Main.vi.

If <b>Wait for Module to Stop?</b> is TRUE, this VI will wait until the module main VI stops, and will timeout at the <b>Timeout to Wait for Stop</b> value. This value defaults to "-1", which means the VI will not timeout, and will always wait until the module main VI stops before completing execution.

Note: The <b>Timeout to Wait for Stop</b> value is ignored if 'Wait for Module to Stop?' is set to FALSE.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Mensajes.lvlib:Show Panel.vi

*Event type:* Request

:imgpath: Mensajes.lvlib_Show Panel.vi.png
image::{imgpath}[Mensajes.lvlib:Show Panel.vi]

*Description:*
++++
Send the Show Panel request to the Module's Main.vi.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Mensajes.lvlib:Hide Panel.vi

*Event type:* Request

:imgpath: Mensajes.lvlib_Hide Panel.vi.png
image::{imgpath}[Mensajes.lvlib:Hide Panel.vi]

*Description:*
++++
Send the Hide Panel request to the Module's Main.vi.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Mensajes.lvlib:Get Module Execution Status.vi

*Event type:* Request

:imgpath: Mensajes.lvlib_Get Module Execution Status.vi.png
image::{imgpath}[Mensajes.lvlib:Get Module Execution Status.vi]

*Description:*
++++
Fire the Get Module Execution Status request.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Mensajes.lvlib:Show Diagram.vi

*Event type:* Request

:imgpath: Mensajes.lvlib_Show Diagram.vi.png
image::{imgpath}[Mensajes.lvlib:Show Diagram.vi]

*Description:*
++++
This VI tells the Module to show its block diagram to facilitate troubleshooting (add probes, breakpoints, highlight execution, etc).

_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Mensajes.lvlib:Publicar mensaje.vi

*Event type:* Request

:imgpath: Mensajes.lvlib_Publicar mensaje.vi.png
image::{imgpath}[Mensajes.lvlib:Publicar mensaje.vi]

*Description:*
++++
Publicar un mensaje en el modulo DQMH mensajes
_____
Created using Delacor QMH Event Scripter 5.0.0.112.
++++

===== Mensajes.lvlib:actualizar el credito.vi

*Event type:* Request

:imgpath: Mensajes.lvlib_actualizar el credito.vi.png
image::{imgpath}[Mensajes.lvlib:actualizar el credito.vi]

*Description:*
++++
actulizar el credito dependiedno del dinero ingresado
_____
Created using Delacor QMH Event Scripter 5.0.0.112.
++++

===== Mensajes.lvlib:Compra Realizada.vi

*Event type:* Request

:imgpath: Mensajes.lvlib_Compra Realizada.vi.png
image::{imgpath}[Mensajes.lvlib:Compra Realizada.vi]

*Description:*
++++
Se realizo la compra de un producto del inventario
_____
Created using Delacor QMH Event Scripter 5.0.0.112.
++++

===== Mensajes.lvlib:Module Did Init.vi

*Event type:* Broadcast

:imgpath: Mensajes.lvlib_Module Did Init.vi.png
image::{imgpath}[Mensajes.lvlib:Module Did Init.vi]

*Description:*
++++
Send the Module Did Init event to any VI registered to listen to this module's broadcast events.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Mensajes.lvlib:Status Updated.vi

*Event type:* Broadcast

:imgpath: Mensajes.lvlib_Status Updated.vi.png
image::{imgpath}[Mensajes.lvlib:Status Updated.vi]

*Description:*
++++
Send the Status Updated event to any VI registered to listen to events from the owning module.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Mensajes.lvlib:Error Reported.vi

*Event type:* Broadcast

:imgpath: Mensajes.lvlib_Error Reported.vi.png
image::{imgpath}[Mensajes.lvlib:Error Reported.vi]

*Description:*
++++
Send the Error Reported event to any VI registered to listen to events from the owning module.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Mensajes.lvlib:Module Did Stop.vi

*Event type:* Broadcast

:imgpath: Mensajes.lvlib_Module Did Stop.vi.png
image::{imgpath}[Mensajes.lvlib:Module Did Stop.vi]

*Description:*
++++
Send the Module Did Stop event to any VI registered to listen to this module's broadcast events.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Mensajes.lvlib:Update Module Execution Status.vi

*Event type:* Broadcast

:imgpath: Mensajes.lvlib_Update Module Execution Status.vi.png
image::{imgpath}[Mensajes.lvlib:Update Module Execution Status.vi]

*Description:*
++++
Broadcast event to specify whether or not the module is running.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

==== Monedas.lvlib

===== Monedas.lvlib:Start Module.vi

*Event type:* Not a DQMH Event

:imgpath: Monedas.lvlib_Start Module.vi.png
image::{imgpath}[Monedas.lvlib:Start Module.vi]

*Description:*
++++
Launches the Module Main.vi.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Monedas.lvlib:Stop Module.vi

*Event type:* Not a DQMH Event

:imgpath: Monedas.lvlib_Stop Module.vi.png
image::{imgpath}[Monedas.lvlib:Stop Module.vi]

*Description:*
++++
Send the Stop request to the Module's Main.vi.

If <b>Wait for Module to Stop?</b> is TRUE, this VI will wait until the module main VI stops, and will timeout at the <b>Timeout to Wait for Stop</b> value. This value defaults to "-1", which means the VI will not timeout, and will always wait until the module main VI stops before completing execution.

Note: The <b>Timeout to Wait for Stop</b> value is ignored if 'Wait for Module to Stop?' is set to FALSE.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Monedas.lvlib:Show Panel.vi

*Event type:* Request

:imgpath: Monedas.lvlib_Show Panel.vi.png
image::{imgpath}[Monedas.lvlib:Show Panel.vi]

*Description:*
++++
Send the Show Panel request to the Module's Main.vi.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Monedas.lvlib:Hide Panel.vi

*Event type:* Request

:imgpath: Monedas.lvlib_Hide Panel.vi.png
image::{imgpath}[Monedas.lvlib:Hide Panel.vi]

*Description:*
++++
Send the Hide Panel request to the Module's Main.vi.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Monedas.lvlib:Get Module Execution Status.vi

*Event type:* Request

:imgpath: Monedas.lvlib_Get Module Execution Status.vi.png
image::{imgpath}[Monedas.lvlib:Get Module Execution Status.vi]

*Description:*
++++
Fire the Get Module Execution Status request.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Monedas.lvlib:Show Diagram.vi

*Event type:* Request

:imgpath: Monedas.lvlib_Show Diagram.vi.png
image::{imgpath}[Monedas.lvlib:Show Diagram.vi]

*Description:*
++++
This VI tells the Module to show its block diagram to facilitate troubleshooting (add probes, breakpoints, highlight execution, etc).

_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Monedas.lvlib:botones uno, dos, tres, cuatro.vi

*Event type:* Request

:imgpath: Monedas.lvlib_botones uno, dos, tres, cuatro.vi.png
image::{imgpath}[Monedas.lvlib:botones uno, dos, tres, cuatro.vi]

*Description:*
++++
numero de moneda presionada
_____
Created using Delacor QMH Event Scripter 5.0.0.112.
++++

===== Monedas.lvlib:Set Coins Valuessssss.vi

*Event type:* Request

:imgpath: Monedas.lvlib_Set Coins Valuessssss.vi.png
image::{imgpath}[Monedas.lvlib:Set Coins Valuessssss.vi]

*Description:*
++++
Sets the values of the coins and the boolean text on them
_____
Created using Delacor QMH Event Scripter 5.0.0.112.
++++

===== Monedas.lvlib:Module Did Init.vi

*Event type:* Broadcast

:imgpath: Monedas.lvlib_Module Did Init.vi.png
image::{imgpath}[Monedas.lvlib:Module Did Init.vi]

*Description:*
++++
Send the Module Did Init event to any VI registered to listen to this module's broadcast events.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Monedas.lvlib:Status Updated.vi

*Event type:* Broadcast

:imgpath: Monedas.lvlib_Status Updated.vi.png
image::{imgpath}[Monedas.lvlib:Status Updated.vi]

*Description:*
++++
Send the Status Updated event to any VI registered to listen to events from the owning module.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Monedas.lvlib:Error Reported.vi

*Event type:* Broadcast

:imgpath: Monedas.lvlib_Error Reported.vi.png
image::{imgpath}[Monedas.lvlib:Error Reported.vi]

*Description:*
++++
Send the Error Reported event to any VI registered to listen to events from the owning module.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Monedas.lvlib:Module Did Stop.vi

*Event type:* Broadcast

:imgpath: Monedas.lvlib_Module Did Stop.vi.png
image::{imgpath}[Monedas.lvlib:Module Did Stop.vi]

*Description:*
++++
Send the Module Did Stop event to any VI registered to listen to this module's broadcast events.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Monedas.lvlib:Update Module Execution Status.vi

*Event type:* Broadcast

:imgpath: Monedas.lvlib_Update Module Execution Status.vi.png
image::{imgpath}[Monedas.lvlib:Update Module Execution Status.vi]

*Description:*
++++
Broadcast event to specify whether or not the module is running.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

==== Producto.lvlib

===== Producto.lvlib:Start Module.vi

*Event type:* Not a DQMH Event

:imgpath: Producto.lvlib_Start Module.vi.png
image::{imgpath}[Producto.lvlib:Start Module.vi]

*Description:*
++++
Launches the Module Main.vi.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Producto.lvlib:Stop Module.vi

*Event type:* Not a DQMH Event

:imgpath: Producto.lvlib_Stop Module.vi.png
image::{imgpath}[Producto.lvlib:Stop Module.vi]

*Description:*
++++
Send the Stop request to the Module's Main.vi.

If <b>Wait for Module to Stop?</b> is TRUE, this VI will wait until the module main VI stops, and will timeout at the <b>Timeout to Wait for Stop</b> value. This value defaults to "-1", which means the VI will not timeout, and will always wait until the module main VI stops before completing execution.

Note: The <b>Timeout to Wait for Stop</b> value is ignored if 'Wait for Module to Stop?' is set to FALSE.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Producto.lvlib:Show Panel.vi

*Event type:* Request

:imgpath: Producto.lvlib_Show Panel.vi.png
image::{imgpath}[Producto.lvlib:Show Panel.vi]

*Description:*
++++
Send the Show Panel request to the Module's Main.vi.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Producto.lvlib:Hide Panel.vi

*Event type:* Request

:imgpath: Producto.lvlib_Hide Panel.vi.png
image::{imgpath}[Producto.lvlib:Hide Panel.vi]

*Description:*
++++
Send the Hide Panel request to the Module's Main.vi.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Producto.lvlib:Get Module Execution Status.vi

*Event type:* Request

:imgpath: Producto.lvlib_Get Module Execution Status.vi.png
image::{imgpath}[Producto.lvlib:Get Module Execution Status.vi]

*Description:*
++++
Fire the Get Module Execution Status request.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Producto.lvlib:Show Diagram.vi

*Event type:* Request

:imgpath: Producto.lvlib_Show Diagram.vi.png
image::{imgpath}[Producto.lvlib:Show Diagram.vi]

*Description:*
++++
This VI tells the Module to show its block diagram to facilitate troubleshooting (add probes, breakpoints, highlight execution, etc).

_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Producto.lvlib:Set Products.vi

*Event type:* Request

:imgpath: Producto.lvlib_Set Products.vi.png
image::{imgpath}[Producto.lvlib:Set Products.vi]

*Description:*
++++
seleccionar productos
_____
Created using Delacor QMH Event Scripter 5.0.0.112.
++++

===== Producto.lvlib:Actualizar inventario.vi

*Event type:* Request

:imgpath: Producto.lvlib_Actualizar inventario.vi.png
image::{imgpath}[Producto.lvlib:Actualizar inventario.vi]

*Description:*
++++
Se actuliza los valores del inventario, del sql
_____
Created using Delacor QMH Event Scripter 5.0.0.112.
++++

===== Producto.lvlib:Module Did Init.vi

*Event type:* Broadcast

:imgpath: Producto.lvlib_Module Did Init.vi.png
image::{imgpath}[Producto.lvlib:Module Did Init.vi]

*Description:*
++++
Send the Module Did Init event to any VI registered to listen to this module's broadcast events.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Producto.lvlib:Status Updated.vi

*Event type:* Broadcast

:imgpath: Producto.lvlib_Status Updated.vi.png
image::{imgpath}[Producto.lvlib:Status Updated.vi]

*Description:*
++++
Send the Status Updated event to any VI registered to listen to events from the owning module.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Producto.lvlib:Error Reported.vi

*Event type:* Broadcast

:imgpath: Producto.lvlib_Error Reported.vi.png
image::{imgpath}[Producto.lvlib:Error Reported.vi]

*Description:*
++++
Send the Error Reported event to any VI registered to listen to events from the owning module.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Producto.lvlib:Module Did Stop.vi

*Event type:* Broadcast

:imgpath: Producto.lvlib_Module Did Stop.vi.png
image::{imgpath}[Producto.lvlib:Module Did Stop.vi]

*Description:*
++++
Send the Module Did Stop event to any VI registered to listen to this module's broadcast events.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Producto.lvlib:Update Module Execution Status.vi

*Event type:* Broadcast

:imgpath: Producto.lvlib_Update Module Execution Status.vi.png
image::{imgpath}[Producto.lvlib:Update Module Execution Status.vi]

*Description:*
++++
Broadcast event to specify whether or not the module is running.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

==== UI.lvlib

===== UI.lvlib:Start Module.vi

*Event type:* Not a DQMH Event

:imgpath: UI.lvlib_Start Module.vi.png
image::{imgpath}[UI.lvlib:Start Module.vi]

*Description:*
++++
Launches the Module Main.vi.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== UI.lvlib:Stop Module.vi

*Event type:* Not a DQMH Event

:imgpath: UI.lvlib_Stop Module.vi.png
image::{imgpath}[UI.lvlib:Stop Module.vi]

*Description:*
++++
Send the Stop request to the Module's Main.vi.

If <b>Wait for Module to Stop?</b> is TRUE, this VI will wait until the module main VI stops, and will timeout at the <b>Timeout to Wait for Stop</b> value. This value defaults to "-1", which means the VI will not timeout, and will always wait until the module main VI stops before completing execution.

Note: The <b>Timeout to Wait for Stop</b> value is ignored if 'Wait for Module to Stop?' is set to FALSE.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== UI.lvlib:Show Panel.vi

*Event type:* Request

:imgpath: UI.lvlib_Show Panel.vi.png
image::{imgpath}[UI.lvlib:Show Panel.vi]

*Description:*
++++
Send the Show Panel request to the Module's Main.vi.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== UI.lvlib:Hide Panel.vi

*Event type:* Request

:imgpath: UI.lvlib_Hide Panel.vi.png
image::{imgpath}[UI.lvlib:Hide Panel.vi]

*Description:*
++++
Send the Hide Panel request to the Module's Main.vi.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== UI.lvlib:Get Module Execution Status.vi

*Event type:* Request

:imgpath: UI.lvlib_Get Module Execution Status.vi.png
image::{imgpath}[UI.lvlib:Get Module Execution Status.vi]

*Description:*
++++
Fire the Get Module Execution Status request.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== UI.lvlib:Show Diagram.vi

*Event type:* Request

:imgpath: UI.lvlib_Show Diagram.vi.png
image::{imgpath}[UI.lvlib:Show Diagram.vi]

*Description:*
++++
This VI tells the Module to show its block diagram to facilitate troubleshooting (add probes, breakpoints, highlight execution, etc).

_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== UI.lvlib:Module Did Init.vi

*Event type:* Broadcast

:imgpath: UI.lvlib_Module Did Init.vi.png
image::{imgpath}[UI.lvlib:Module Did Init.vi]

*Description:*
++++
Send the Module Did Init event to any VI registered to listen to this module's broadcast events.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== UI.lvlib:Status Updated.vi

*Event type:* Broadcast

:imgpath: UI.lvlib_Status Updated.vi.png
image::{imgpath}[UI.lvlib:Status Updated.vi]

*Description:*
++++
Send the Status Updated event to any VI registered to listen to events from the owning module.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== UI.lvlib:Error Reported.vi

*Event type:* Broadcast

:imgpath: UI.lvlib_Error Reported.vi.png
image::{imgpath}[UI.lvlib:Error Reported.vi]

*Description:*
++++
Send the Error Reported event to any VI registered to listen to events from the owning module.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== UI.lvlib:Module Did Stop.vi

*Event type:* Broadcast

:imgpath: UI.lvlib_Module Did Stop.vi.png
image::{imgpath}[UI.lvlib:Module Did Stop.vi]

*Description:*
++++
Send the Module Did Stop event to any VI registered to listen to this module's broadcast events.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== UI.lvlib:Update Module Execution Status.vi

*Event type:* Broadcast

:imgpath: UI.lvlib_Update Module Execution Status.vi.png
image::{imgpath}[UI.lvlib:Update Module Execution Status.vi]

*Description:*
++++
Broadcast event to specify whether or not the module is running.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

=== Libraries

This section describes libraries public VIs.

==== DataBaseSQLlite.lvlib

===== DataBaseSQLlite.lvlib:ActualizarCostosDB.vi

:imgpath: DataBaseSQLlite.lvlib_ActualizarCostosDB.vi.png
image::{imgpath}[DataBaseSQLlite.lvlib:ActualizarCostosDB.vi]

*Description:*
No description found (add content in VI description)

===== DataBaseSQLlite.lvlib:ActualizarInventarioDBsql.vi

:imgpath: DataBaseSQLlite.lvlib_ActualizarInventarioDBsql.vi.png
image::{imgpath}[DataBaseSQLlite.lvlib:ActualizarInventarioDBsql.vi]

*Description:*
No description found (add content in VI description)

===== DataBaseSQLlite.lvlib:Agregar Producto a DB.vi

:imgpath: DataBaseSQLlite.lvlib_Agregar Producto a DB.vi.png
image::{imgpath}[DataBaseSQLlite.lvlib:Agregar Producto a DB.vi]

*Description:*
No description found (add content in VI description)

===== DataBaseSQLlite.lvlib:BorrarenDBsql.vi

:imgpath: DataBaseSQLlite.lvlib_BorrarenDBsql.vi.png
image::{imgpath}[DataBaseSQLlite.lvlib:BorrarenDBsql.vi]

*Description:*
No description found (add content in VI description)

===== DataBaseSQLlite.lvlib:BuscarenInventario.vi

:imgpath: DataBaseSQLlite.lvlib_BuscarenInventario.vi.png
image::{imgpath}[DataBaseSQLlite.lvlib:BuscarenInventario.vi]

*Description:*
No description found (add content in VI description)

===== DataBaseSQLlite.lvlib:DataBasePATH.vi

:imgpath: DataBaseSQLlite.lvlib_DataBasePATH.vi.png
image::{imgpath}[DataBaseSQLlite.lvlib:DataBasePATH.vi]

*Description:*
No description found (add content in VI description)

===== DataBaseSQLlite.lvlib:ObtenerInformacionProducto.vi

:imgpath: DataBaseSQLlite.lvlib_ObtenerInformacionProducto.vi.png
image::{imgpath}[DataBaseSQLlite.lvlib:ObtenerInformacionProducto.vi]

*Description:*
No description found (add content in VI description)

=== Classes

This section describes classes public VIs.

== Legal Information

=== Document creation

This document has been generated using the following tools.

==== Antidoc

Project website: https://wovalab.gitlab.io/open-source/labview-doc-generator/[Antidoc] 

Maintainer website: https://wovalab.com[Wovalab] 

BSD 3-Clause License

Copyright (C) 2019, Wovalab,
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

* Neither the name of the copyright holder nor the names of its
  contributors may be used to endorse or promote products derived from
  this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


==== Asciidoc for LabVIEW(TM)

Project website: https://wovalab.gitlab.io/open-source/asciidoc-toolkit/[Asciidoc toolkit] 

Maintainer website: https://wovalab.com[Wovalab] 

BSD 3-Clause License

Copyright (C) 2019, Wovalab,
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

* Neither the name of the copyright holder nor the names of its
  contributors may be used to endorse or promote products derived from
  this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


==== Graph Builder

Project website: https://gitlab.com/cgambini/graph-builder[Graph Builder]

BSD 3-Clause License

Copyright (c) 2020, Cyril GAMBINI
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

* Neither the name of the copyright holder nor the names of its
  contributors may be used to endorse or promote products derived from
  this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


=== Product used in the project

The documented project has been developed with the following products.

==== DQMH(R)

Copyright (C) 2015-2020 by Delacor, LLC. All Rights Reserved.

Find more details on https://delacor.com/products/dqmh/[Delacor] website

